### ISSUE TITLE
UI bug: Maximise window hint overlay disappears shortly after its displayed.

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-web-browser#378]
## Expected Behavior
When you drag a window to the top of the app to show the maximise hint overlay, it should persist (like it does on the left and right).

## Current Behavior
After about a second, the overlay dissapears.

## Steps to Reproduce
1. Drag a window to the top

2. and keep the mouse held down

3. maximise overlay appears

4. maximise overlay disappears a moment later.

N/A

**Comment by danielfebrero** [comment]
Ok in fact, there is a bug but not exactly here, because what you describe as a bug is in fact a feature. If you are further down in the board, and you drag a window to the top, you have one second to drop it and maximize it. If not, it start to scroll up.
The bug I would say is when you are at the top of the board. You cannot scroll more, so the overlay shouldn't disapear. I will submit a fix.
